swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>'
paths:
  /accounts/{username}/{password}:
    get:
      parameters:
        - description: Username
          in: path
          name: username
          required: true
          type: string
        - description: Password
          in: path
          name: password
          required: true
          type: string
      responses:
        '200':
          description: No response was specified
      tags:
        - Click "TRY IT OUT" then "Excute" to Login
