swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>
    <div class="form-container">
    <form method="post" action="">
    <input type="text" name="username" placeholder="enter username"><br/><br/>
    <input type="text" name="password" placeholder="enter password"><br/><br/>
    <input type="submit" name="submit" value="submit"/>
</form>
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
