swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: '<div class="login-form">
    <div class="heading">
        <h1>HTML Injection : Fake Login</h1>
    </div>
    <div class="form-container">
     <p>You can get pro account by sending us 10 USD through our official paypal attacker@attacker.com.<br>For more information Sign in and claim your offer from <a href="attacker.com">here</a></p><p>Regards</p><p>Invoiced Admin</p> 
    </div>
</div>'
paths:
  /:
    post:
      responses:
        '200':
          description: Login successfula
